(function(a){var g={url:!1,callback:!1,target:!1,duration:120,on:"mouseover",touch:!0,onZoomIn:!1,onZoomOut:!1,magnify:1};a.zoom=function(g,h,c,b){var d,f,k,e,m,n,q,r=a(g).css("position"),l=a(h);return g.style.position=/(absolute|fixed)/.test(r)?r:"relative",g.style.overflow="hidden",c.style.width=c.style.height="",a(c).addClass("zoomImg").css({position:"absolute",top:0,left:0,opacity:0,width:c.width*b,height:c.height*b,border:"none",maxWidth:"none",maxHeight:"none"}).appendTo(g),{init:function(){f=
a(g).outerWidth();d=a(g).outerHeight();h===g?(e=f,k=d):(e=l.outerWidth(),k=l.outerHeight());m=(c.width-f)/e;n=(c.height-d)/k;q=l.offset()},move:function(a){var b=a.pageX-q.left;a=a.pageY-q.top;a=Math.max(Math.min(a,k),0);b=Math.max(Math.min(b,e),0);try{c.style.left=b*-m+"px",c.style.top=a*-n+"px"}catch(d){}}}};a.fn.zoom=function(p){return this.each(function(){var h,c=a.extend({},g,p||{}),b=c.target||this,d=this,f=a(d),k=document.createElement("img"),e=a(k),m=!1,n=!1;(c.url||(h=f.find("img"),h[0]&&
(c.url=h.data("src")||h.attr("src")),c.url))&&(function(){var a=b.style.position,c=b.style.overflow;f.one("zoom.destroy",function(){f.off(".zoom");b.style.position=a;b.style.overflow=c;e.remove()})}(),k.onload=function(){function g(b){l.init();l.move(b);e.stop().fadeTo(a.support.opacity?c.duration:0,1,a.isFunction(c.onZoomIn)?c.onZoomIn.call(k):!1)}function h(){e.stop().fadeTo(c.duration,0,a.isFunction(c.onZoomOut)?c.onZoomOut.call(k):!1)}var l=a.zoom(b,d,k,c.magnify);"grab"===c.on?f.on("mousedown.zoom",
function(b){1===b.which&&(a(document).one("mouseup.zoom",function(){h();a(document).off("mousemove.zoom",l.move)}),g(b),a(document).on("mousemove.zoom",l.move),b.preventDefault())}):"click"===c.on?f.on("click.zoom",function(b){return m?void 0:(m=!0,g(b),a(document).on("mousemove.zoom",l.move),a(document).one("click.zoom",function(){h();m=!1;a(document).off("mousemove.zoom",l.move)}),!1)}):"toggle"===c.on?f.on("click.zoom",function(a){m?h():g(a);m=!m}):"mouseover"===c.on&&(l.init(),f.on("mouseenter.zoom",
g).on("mouseleave.zoom",h).on("mousemove.zoom",l.move));c.touch&&f.on("touchstart.zoom",function(a){a.preventDefault();n?(n=!1,h()):(n=!0,g(a.originalEvent.touches[0]||a.originalEvent.changedTouches[0]))}).on("touchmove.zoom",function(a){a.preventDefault();l.move(a.originalEvent.touches[0]||a.originalEvent.changedTouches[0])});a.isFunction(c.callback)&&c.callback.call(k)},k.src=c.url)})};a.fn.zoom.defaults=g})(window.jQuery);
!function(a,g,p,h){var c=a(g);a.fn.lazyload=function(b){function d(){var b=0;k.each(function(){var c=a(this);if(!(e.skip_invisible&&!c.is(":visible")||a.abovethetop(this,e)||a.leftofbegin(this,e)))if(a.belowthefold(this,e)||a.rightoffold(this,e)){if(++b>e.failure_limit)return!1}else c.trigger("appear"),b=0})}var f,k=this,e={threshold:0,failure_limit:0,event:"scroll",effect:"show",container:g,data_attribute:"original",skip_invisible:!0,appear:null,load:null,placeholder:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"};
return b&&(h!==b.failurelimit&&(b.failure_limit=b.failurelimit,delete b.failurelimit),h!==b.effectspeed&&(b.effect_speed=b.effectspeed,delete b.effectspeed),a.extend(e,b)),f=e.container===h||e.container===g?c:a(e.container),0===e.event.indexOf("scroll")&&f.bind(e.event,function(){return d()}),this.each(function(){var b=this,c=a(b);b.loaded=!1;(c.attr("src")===h||!1===c.attr("src"))&&c.is("img")&&c.attr("src",e.placeholder);c.one("appear",function(){this.loaded||(e.appear&&e.appear.call(b,k.length,
e),a("<img />").bind("load",function(){var d=c.attr("data-"+e.data_attribute);c.hide();c.is("img")?c.attr("src",d):c.css("background-image","url('"+d+"')");c[e.effect](e.effect_speed);b.loaded=!0;d=a.grep(k,function(a){return!a.loaded});(k=a(d),e.load)&&e.load.call(b,k.length,e)}).attr("src",c.attr("data-"+e.data_attribute)))});0!==e.event.indexOf("scroll")&&c.bind(e.event,function(){b.loaded||c.trigger("appear")})}),c.bind("resize",function(){d()}),/(?:iphone|ipod|ipad).*os 5/gi.test(navigator.appVersion)&&
c.bind("pageshow",function(b){b.originalEvent&&b.originalEvent.persisted&&k.each(function(){a(this).trigger("appear")})}),a(p).ready(function(){d()}),this};a.belowthefold=function(b,d){var f;return f=d.container===h||d.container===g?(g.innerHeight?g.innerHeight:c.height())+c.scrollTop():a(d.container).offset().top+a(d.container).height(),f<=a(b).offset().top-d.threshold};a.rightoffold=function(b,d){var f;return f=d.container===h||d.container===g?c.width()+c.scrollLeft():a(d.container).offset().left+
a(d.container).width(),f<=a(b).offset().left-d.threshold};a.abovethetop=function(b,d){var f;return f=d.container===h||d.container===g?c.scrollTop():a(d.container).offset().top,f>=a(b).offset().top+d.threshold+a(b).height()};a.leftofbegin=function(b,d){var f;return f=d.container===h||d.container===g?c.scrollLeft():a(d.container).offset().left,f>=a(b).offset().left+d.threshold+a(b).width()};a.inviewport=function(b,c){return!(a.rightoffold(b,c)||a.leftofbegin(b,c)||a.belowthefold(b,c)||a.abovethetop(b,
c))};a.extend(a.expr[":"],{"below-the-fold":function(b){return a.belowthefold(b,{threshold:0})},"above-the-top":function(b){return!a.belowthefold(b,{threshold:0})},"right-of-screen":function(b){return a.rightoffold(b,{threshold:0})},"left-of-screen":function(b){return!a.rightoffold(b,{threshold:0})},"in-viewport":function(b){return a.inviewport(b,{threshold:0})},"above-the-fold":function(b){return!a.belowthefold(b,{threshold:0})},"right-of-fold":function(b){return a.rightoffold(b,{threshold:0})},
"left-of-fold":function(b){return!a.rightoffold(b,{threshold:0})}})}(jQuery,window,document);